stages: 
    - deploy
deploy:
    stage: deploy
    script:
      - mvn install
      - mvn clean package
      - rm -rf /root/spring_boot/*.jar
      - rm -rf /etc/init.d/tinymall-*
      - cp -rf tinymall-wx-api/target/tinymall-wx-api-*-exec.jar /root/spring_boot/tinymall-wx-api.jar
      - sudo chmod 777 /root/spring_boot/*.jar
      - sudo ln -f -s /root/spring_boot/tinymall-wx-api.jar /etc/init.d/tinymall-wx-api
      - sudo /etc/init.d/tinymall-wx-api restart
      - sudo /etc/init.d/tinymall-admin-api restart
      - systemctl stop nginx
      - rm -rf /root/nginx_web/
      - cd tinymall-admin
      - cnpm install
      - cnpm run build:dep
      - mkdir /root/nginx_web
      - cp -rf dist/* /root/nginx_web
      - sudo chmod 777 /root/nginx_web
      - systemctl restart nginx
    tags:
      - tinymall